[workspace]
package.version = "0.0.0"
package.edition = "2021"
package.authors = ["Team Minty"]
package.license = "ISC"
dependencies.common = { path = "crates/common", package = "hypatia-common" }
resolver = "2"
members = [
    "crates/*"
]